#!/bin/sh -x

# cd /var/named/chroot/dev
# mknod null c 1 3
# mknod random c 1 8
# mknod zero c 1 5
# chmod 666 null random
# chown -R named.named /var/named /var/run

c=${DESTDIR}${PREFIX}/var/named

mkdir -p ${c} 

mv chroot ${c}

#chown -R tops.users  ${c}
#mkdir -p ${c}/chroot/dev && cd ${c}/dev
#mknod null c 1 3
#mknod random c 1 8
#mknod zero c 1 5
#chmod 666 null random

