#!/bin/sh

#exec > /tmp/tops-ocaml-build.log 2>&1


./configure -cc "gcc -fPIC" -aspp "gcc -fPIC -c" || exit 1
make world || exit 1
make opt || exit 1
mkdir -p  $DESTDIR/usr/local || exit 1
make install PREFIX=$DESTDIR/usr/local || exit 1
