#!/bin/sh

./configure --prefix=/usr/local \
    --enable-ipv6 \
    --enable-unicode=ucs4 \
    --enable-shared \
    --with-system-ffi \
    --with-system-expat \

export CFLAGS="$CFLAGS `pkg-config --cflags openssl`"
make OPT="$CFLAGS -DNDEBUG"
mkdir -p $DESTDIR/usr/local/bin
cp ./static-python $DESTDIR/usr/local/bin/
make -j2 install DESTDIR=$DESTDIR
