#!/bin/sh

cd daemontools-$PACKAGEVERSION
sed -i -e 's#gcc#gcc -include /usr/include/errno.h #g' src/conf-cc
sh package/compile
mkdir -p $DESTDIR/usr/local/bin
# sould use fakeroot multipkg 
#install -m755 -oroot command/* $DESTDIR/usr/local/bin
install -m755 command/* $DESTDIR/usr/local/bin

