#!/bin/sh

TARGETS="axfrdns axfrdns-conf axfr-get dnscache dnscache-conf dnsfilter dnsip dnsipq dnsmx dnsname dnsq dnsqr dnstrace dnstracesort dnstxt pickdns pickdns-conf pickdns-data random-ip rbldns rbldns-conf rbldns-data tinydns tinydns-conf tinydns-data tinydns-edit tinydns-get walldns walldns-conf"

make
mkdir -p $DESTDIR/usr/local/bin
install -m755 -oroot $TARGETS $DESTDIR/usr/local/bin

mkdir -p $DESTDIR/etc/service/dnscache/root/servers
cat > $DESTDIR/etc/service/dnscache/root/servers/@ <<EOF
198.41.0.4
192.228.79.201
192.33.4.12
128.8.10.90
192.203.230.10
192.5.5.241
192.112.36.4
128.63.2.53
192.36.148.17
192.58.128.30
193.0.14.129
198.32.64.12
202.12.27.33
EOF

