#+TITLE:     book_reading.org
#+AUTHOR:    Ting Yu
#+EMAIL:     16667737@qq.com
#+DATE:      2014-10-07 二
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:


* 读书

** 《乌合之众：大众心理学研究》

讨论观念的形成：
#+BEGIN_VERSE
在我们的生活中，能够帮助我们走向成功的条件是判断力，是经验，是开拓精神和个
性！而这些优良品质，偏偏是不能从死啃书本中得来的，教科书和字典固然可以充当
有用的参考工具，但长久把它们放在脑子里却没有任何用处。 

那么，我们该如何让孩子们接受到有益的教育，让它帮助孩子们获得正确的观念呢？ 
要知道，观念只有在自然而正常的环境中才能形成。 因此，我们需要年轻人每天从
工厂、矿山、法庭、书房、建筑工地和医院获得大量的感官印象；他得亲眼看到各种
工具、材料和操作；他得与顾客、工作者和劳动者在一起，不管他们干得是好是坏，
也不管他们是赚是赔。 
　　 
只有采用这种方式，孩子们才能对那些从眼睛、耳朵、双手甚至味觉中得到的各种细
节，有些微不足道的理解。学习者在不知不觉中获得了这些细节，默默地推敲，在心
中逐渐成形，并且或迟或早会产生出一些提示，让他们着手新的组合、简化、创意、
改进或发明.
　 
而我们的年轻人，却恰恰在最能出成果的年纪，被剥夺了所有这些宝贵的接触、所有这
些不可缺少的学习因素，因为有七八年的时间他一直被关在学校里，切断了一切亲身体
验的机会，因此对于世间的人和事，对于控制这些人和事的各种办法，不可能得到鲜明
而准确的理解。 
#+END_VERSE

上面这段话来自 乌合之众：大众心理学研究 P63 页。 注意这里着重讨论的是观念的形
成, 这些观点和王阳明的知行合一是异曲同工之理。

** 《古今数学思想，第一册》

笛卡尔我一直以为仅仅是个数学家（在笛卡尔积的引导下，我还给局限成了离散数学家），
但是在读《古今数学思想，第一册》的时候被告知原来笛卡尔是第一个杰出的近代哲学家，
是近代生物学的奠基人，是第一流的物理学家但只偶然地是个数学家。尴尬。

把公理引入哲学。

逻辑和真理的关系：

笛卡尔认为：逻辑不能提供基本的真理。逻辑本身是无结果的：“谈到逻辑，他的三段论
和其他观念的大部分，与其说是用来探索未知的东西，不如说是用来交流已知的东西，
或者用来无判断地空谈我们所不知道的东西.”  

所以投资逻辑也是这样，用来交流描述已知的东西
