#+TITLE:     org-my-life.org
#+AUTHOR:    Ting Yu
#+EMAIL:     16667737@qq.com
#+DATE:      2014-10-13 一
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

* Orgnization Your Life.
** 基本场景.

当面对 org agenda 的时候我们应该从那几个方面思考.

*** 用 <f12> 来，觉察自己, 反省自己  'org-agenda (日程，议程)
     有意识的构建，并且让自己生活在自己的日程下. 这个日程需要包括的几个方面.
     对于 emacs 下的 org-mode 来说就是需要几个  [[file:/sudo:root@localhost:/home/yuting/.emacs.d/org-init.el::(setq%20org-agenda-files%20(list%20"~/org/"%20))][org-agenda-files]] 的定义.目前
     我的 agenda-files 就是 ~/org/ 下所有的文件. 当激活 f12 的时候,具体介绍
     在[[info:org#Agenda%20Views][info:org#Agenda Views]]
     
     - <space> 列出所有的agenda 视图.
     - a 列出以日期为主的日程报告. 反复 A 就是向报告中Append 新的agenda section
     - t 列出所有的当前的todo 标签中定义的条目进行组织.

*** Capture 日常流水帐的思考场景. C-c c j

C-c c j 进入到 Journal 模式写下当下一点的 Journal item 然后保存在 diary.org 文件中.
心理建设: 觉察于自省的分别.  觉察是把我放到自己当中，而自省是把我拿到自己的对面.
写流水账的时候先觉察发生在自己身边的各种事情，然后反省其中是否有对自己的影响.

*** Capture 一个新的 TODO/NOTE 的场景.

TODO 可以来源于两个方向，一个是在具体的TASK 下面也就是除了 refile.org 文件以外
其他的文件可以看成一个个小小的 project . 这些文件中的TODO 就是该项目下的一个TASK

*** TODO 当进入到某个具体的 node 进行编辑的时候. 需要整理下面的文字.

专注于某个 TODO 章节进行编辑修改的F5（不仅仅是眼不见为净）

  使用 bh/org-todo   <F5>
  org-todo 之后表明这个 items 是自己当前正在进行的一个todo 项目.就好像一个指针
  记录着当前你的todo 所到之处，f12-space 后这个item项会出现在 Task to Archive中.

  恢复可见   bh/widen  <S-F5>

神奇的C-c C-c / C-c C-t (当你不知道当下该干什么的时候cc 之).
   refer to [[http://doc.norang.ca/org-mode.htm][Orgnazie Your Life In Plain Text!]]
   C-c C-c 是给每个 node section 分类.
   C-c C-t 是给每个 node section 分工能
   在不同的行环境下C-c C-c 有着不同的行为. [[info:org#The%20very%20busy%20C-c%20C-c%20key][info:org#The very busy C-c C-c key]]

**** 关于时间上的一些操作.
   + SCHEDULED 的标签会把当前的notes 加入到日历计算中
   + C-c . 然后 S-left/right 可以选择自己要的日期.
   + <> 中的时间表示激活的时间，也就是可以显示在日历中的时间.
   + [] 表示未激活的时间，仅仅是作时间的记录用.
   + -- 表示时间范围.

     clock things

*** TODO Habit 模式养成一个习惯,还没有清楚.
    老规矩先进入到 C-c c h  进入到 habit 模式下. 将habit的文档
    refile 到 refile.org 下.

    
