#+TITLE:     写点什么吧！
#+AUTHOR:    Ting Yu
#+EMAIL:     16667737@qq.com
#+DATE:      2014-10-07 二
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:


* 关于宗教的迷思。

赋闲在家，偶尔看看书柜里的书，有一小部分是和宗教哲学有关系的，但是大部分
都不是什么经典，基本上都是些注解，或者略说之类的，上学的时候对有些书非常
痴迷，没事读上几篇经常有种超脱的感觉。同时期记得老爹炒股的时候时不时也会
拿出个奇怪的类似五行八卦的东西往桌子上一铺，陷入深深的沉思。这两天翻看 A
股历史找到那时候的股市行情颇为不堪，再想想那时候的自己也是学业不顺。

有时候在想是不是人在陷入某种困难的时候，内心脆弱的时候就会默默的皈依于一门
宗教呢？好像也不是，记得有一年部门里来了个领导，用他的话讲基本上也是财务自
由的人了聊到兴趣爱好，其中有两样，一个是关于中医养生，另外一个皈依了佛教，
我和几个朋友私下曾经开玩笑说，咱们这终于来了一个有信仰的人。对于中医了解我
的人知道，我是不愿意探讨的。一来是对中医这两个字有深深的疑虑，二来自己因为
是个中国人，骨子里又深深的烙上了这个印记而没法摆脱。 上了那么多年学，数学里
没有中数西数之分，物理里没有中物，西物之分。甚至于有中国特色的数理化也不曾
见过有哪些妄人提过（文革时期课本除外），偏偏在医学这个领域里出现了中医和西
医的提法并且至今仍然被大家喜闻乐道的。


* 交易心得.

* 乱谈 Meta-Narrative, Mega-Narrative

刚刚看完一个朋友圈中的TED Talk. 

题目是在字典中除去古希腊释义，和姓氏的含义外。另外两重意思

  - 认识论中的 About(its own category).
  - 高阶抽象.(On higher level of abstraction).

罗列一些在计算机领域里常见的 Meta- 前缀的词,及其解释。

Meta-data  are data about data
Meta-programming are writing programs that manipulate programs.
Meta-rule is a rule that governs the application of other rules.

上班的时候我还曾经维护过一个工具叫 metapkg. 套用 X about X 的公式
这就是一个通过公共包属性抽象对多类型包进行打包管理的工具。

在管理岗的时候曾经培训过六顶思考的帽的开会方法这就是典型的
Meta-discussion : discussion about discussion.

够矫情了么? 再来一个更邪乎的.

meta-cognition : (元认知：对思考的思考). 也就是要思考自己的思考方式
，研究自己的研究方式. 换句话说思考什么，研究什么先放一边，只要meta-cognition
够牛，那你cognize啥都很快。听起来很神奇吧？ 

现在回到李世默的TED Talk 中，看看他指的 meta-narrative，又是什么呢？


共产主义，民主，自由，选举这些名词一旦进入到 meta-narrative 传播模式
下为啥基本上没有好结果呢？我这么钟爱的 meta 前缀一和 narrative 合并为
啥就给世界带来这么多困扰呢？ 到底是 meta 出问题了还是 narrative 不好？
 这个 TED Talk 真的是在论述我党执政这么多年来政治体制方面的先进性么？
我们的组织部是用什么机制构建出党内的social leder的呢？ 为何我们的领导
需要锻造30年才能胜任chairman这个位置操作这部国家的机器，而美帝仅仅需要
几个月就能选出一个智商，才华都只是在中国县长水平上的布什做president，
而国家还无大碍？虽然提出了这些问题，但是作为一个有诚意的人却无法简单
回答，甚至没法回答，因为这些问题都是政治上的大哉问,若要敷衍了事你只能
采用 meta-narrative的方法。

写到这，李博士看来并不是在批评或者赞同某种政治上的意识形态，而是在批评
meta-narrative 这种叙事方法，不说政治了，看看生活中我们常见的地域炮的论
述吧：

  - 东北人很猛.
  - 山西人很抠
  - 江浙人精明

你了解中国互联网巨头么？ 然后在看看下面的论述.

 - 腾讯都是靠抄袭做大
 - 淘宝是靠假货才这么兴隆
 - 百度是靠gfw了google生存下来.

演讲看到最后李世默终于透露了自己投资行业的底，我瞬间就明白了，因为这是干
投资的最忌讳的叙事方式，它通常有那么点根据但是结论粗糙武断却又朗朗上口，
时刻影响着你对这个世界的看法，左右着你的头寸。写到这看来 meta-narrative 
根本不是我心仪的那个元叙事,meta这个词一旦走出了计算机的世界，它迅速的就变
得干巴巴的，口号式的，空洞的概念标签，因为它本身又具有高度抽象的特点导致
它常常因为缺乏细节而变得模糊，充满歧义的同时又能产生了一个无法辩驳的断言。
没错这ta 已经不是meta了而是 mega-narrative(宏大叙事):从我们带上红领巾
开始,学到的雷锋，赖宁等等，无不是通过这种途径而了解到的事迹啊。


最后端上两杯清茶 ，拍拍沙发垫子，坐吧，站在朋友的角度我们一起再看一遍这个
演讲，同时想想李博士是不是也陷入到 meta-narrative 中了呢？

