#!/bin/sh

make

TARGETS="addcr argv0 date@ delcr finger@ fixcrio http@ mconnect mconnect-io rblsmtpd recordio tcpcat tcpclient tcprules tcprulescheck tcpserver who@"

mkdir -p $DESTDIR/usr/local/bin/
#install -m755 -oroot $TARGETS $DESTDIR/usr/local/bin/
install -m755  $TARGETS $DESTDIR/usr/local/bin/

